version: '3.4'

services:
  curl:
    image: curlimages/curl:8.3.0
    user: ${DOCKER_USER:-1000}
    # restart: always
    volumes:
      - html:/var/www/html
    command: [
      "/bin/sh",
      "-c",
      "--",
      "trap : TERM INT; while :; do curl http://moodle/admin/cron.php; sleep 60; done & wait"
    ]

  dockerize:
    image: jwilder/dockerize:0.6.1

  mailpit:
    image: axllent/mailpit:v1.8.4
    restart: unless-stopped
    ports:
      - ${HOOK_MAILPIT_UI_PORT:-8025}:8025

  moodle:
    build:
      context: .
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    environment:
      MOODLE_DATABASE_NAME: ${HOOK_MOODLE_MYSQL_DATABASE:-moodle}
      MOODLE_DATABASE_USER: ${HOOK_MOODLE_MYSQL_USER:-moodle}
      MOODLE_DATABASE_PASSWORD: ${HOOK_MOODLE_MYSQL_PASSWORD:-password}
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    ports:
      - ${HOOK_MOODLE_APACHE_PORT:-8080}:80
    volumes:
      - html:/var/www/html
      - moodledata:/var/www/moodledata
    depends_on:
      - mailpit
      - mysql
      - curl

  mysql:
    image: mysql:5.7.43
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${HOOK_MOODLE_MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${HOOK_MOODLE_MYSQL_DATABASE:-moodle}
      MYSQL_USER: ${HOOK_MOODLE_MYSQL_USER:-moodle}
      MYSQL_PASSWORD: ${HOOK_MOODLE_MYSQL_PASSWORD:-password}
    volumes:
      - mysqldata:/var/lib/mysql
    command: >
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_bin
        --innodb_file_format=barracuda
        --innodb_file_per_table=On
        --innodb_large_prefix=On

volumes:
  html:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/moodle/html

  moodledata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/moodle/moodledata

  mysqldata:
    driver: local
