version: '3.4'

services:
  curl:
    image: curlimages/curl:8.3.0
    user: ${DOCKER_USER:-1000}
    restart: always
    volumes:
      - ./data/moodle/html:/var/www/html
    command:
      - /bin/sh
      - -c
      - "trap : TERM INT; while :; do curl http://moodle/admin/cron.php; sleep 60; done & wait"

  dockerize:
    image: jwilder/dockerize:0.6.1

  elasticsearch:
    image: elasticsearch:8.10.1
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
    ports:
      - ${HOOK_RALPH_ELASTICSEARCH_PORT:-9200}:9200
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
    mem_limit: 2g
    ulimits:
      memlock:
        soft: -1
        hard: -1

  hook:
    build:
      context: .
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    environment:
      PYLINTHOME: /app/.pylint.d
      HOOK_MOODLE_URL: ${HOOK_MOODLE_URL:-http://moodle}
      HOOK_MOODLE_WEBSERVICE_TOKEN: ${HOOK_MOODLE_WEBSERVICE_TOKEN:-32323232323232323232323232323232}
    ports:
      - ${HOOK_API_PORT:-8000}:8000
    volumes:
      - .:/app
    command: [
      "uvicorn",
      "hook.main:app",
      "--host",
      "0.0.0.0",
      "--port",
      "8000",
      "--reload"
    ]
    depends_on:
      - moodle

  mailpit:
    image: axllent/mailpit:v1.8.4
    restart: unless-stopped
    ports:
      - ${HOOK_MAILPIT_UI_PORT:-8025}:8025

  moodle:
    build:
      context: ./config/moodle
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    environment:
      MOODLE_DATABASE_NAME: ${HOOK_MOODLE_MYSQL_DATABASE:-moodle}
      MOODLE_DATABASE_USER: ${HOOK_MOODLE_MYSQL_USER:-moodle}
      MOODLE_DATABASE_PASSWORD: ${HOOK_MOODLE_MYSQL_PASSWORD:-password}
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    ports:
      - ${HOOK_MOODLE_APACHE_PORT:-8080}:80
    volumes:
      - ./data/moodle/html:/var/www/html
      - ./data/moodle/moodledata:/var/www/moodledata
    depends_on:
      - mailpit
      - mysql
      - curl
      - ralph

  mysql:
    image: mysql:5.7.43
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${HOOK_MOODLE_MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${HOOK_MOODLE_MYSQL_DATABASE:-moodle}
      MYSQL_USER: ${HOOK_MOODLE_MYSQL_USER:-moodle}
      MYSQL_PASSWORD: ${HOOK_MOODLE_MYSQL_PASSWORD:-password}
    volumes:
      - mysqldata:/var/lib/mysql
    command: >
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_bin
        --innodb_file_format=barracuda
        --innodb_file_per_table=On
        --innodb_large_prefix=On

  ralph:
    image: fundocker/ralph:3.9.0
    user: ${DOCKER_USER:-1000}
    environment:
      RALPH_AUTH_FILE: /app/auth.json
      RALPH_BACKENDS__DATABASE__ES__HOSTS: http://elasticsearch:9200
      RALPH_BACKENDS__DATABASE__ES__INDEX: ${HOOK_RALPH_ELASTICSEARCH_INDEX:-statements}
      RALPH_RUNSERVER_PORT: 80
    command:
      - ralph
      - "-v"
      - DEBUG
      - runserver
      - "-b"
      - "es"
    volumes:
      - ./data/ralph:/app
    depends_on:
      - elasticsearch

volumes:
  elasticsearchdata:
    driver: local

  mysqldata:
    driver: local
